version: '3.4'

x-disabled: &disabled_service
  entrypoint: ["echo", "service is disabled"]

services:
  web:
    volumes:
      - .:/app

  ethereum: *disabled_service
  raiden: *disabled_service
  celery: *disabled_service
  celery_beat: *disabled_service
  job_listen_events: *disabled_service
